import { HeartPulse } from "lucide-react"

/** Static date so server- and client-rendered sheets never mismatch. */
export const DOCUMENT_ISSUED_DATE = "August 11, 2026"

export function SheetHeader({ recordNo }: { recordNo: string }) {
  return (
    <header className="flex items-start justify-between gap-4 border-b border-neutral-300 pb-4">
      <div className="flex items-center gap-3">
        <span className="flex size-10 items-center justify-center rounded-lg bg-primary text-primary-foreground">
          <HeartPulse className="size-5" />
        </span>
        <div>
          <p className="font-heading text-lg font-bold text-foreground">
            MedCare Health
          </p>
          <p className="text-label-caps uppercase tracking-widest text-muted-foreground">
            Patient Portal
          </p>
        </div>
      </div>
      <div className="pr-8 text-right">
        <p className="text-sm font-semibold text-foreground">
          Record No. {recordNo}
        </p>
        <p className="mt-0.5 text-xs text-muted-foreground">
          Issued: {DOCUMENT_ISSUED_DATE}
        </p>
      </div>
    </header>
  )
}

export function SheetSectionTitle({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <p className="border-b border-neutral-300 pb-1.5 text-label-caps uppercase tracking-widest text-primary">
      {children}
    </p>
  )
}

export function SheetFooter() {
  return (
    <footer className="mt-auto flex items-end justify-between border-t border-neutral-300 pt-3 text-xs text-muted-foreground">
      <p>Generated by MedCare Health Portal</p>
      <p>Page 1 of 1</p>
    </footer>
  )
}
